name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions1:
    
  
    uses: lokiharsha/reusable-workflows/.github/workflows/on-push-job.yml@main

